### ISSUE TITLE
IllegalArgumentException on startup

### ISSUE THREAD

**Issue by ZugPilot** [Nova41/SnowLeopard#22]
java.lang.IllegalArgumentException: Illegal character in path at index 7: plugins\SnowLeopardR//category
        at java.net.URI.create(Unknown Source) ~[?:1.8.0_241]
        at com.nova41.bukkitdev.slr.util.SLFiles.getSeparatedPath(SLFiles.java:32) ~[?:?]
        at com.nova41.bukkitdev.slr.util.SLFiles.createDirectoryIfAbsent(SLFiles.java:37) ~[?:?]
        at com.nova41.bukkitdev.slr.SnowLeopardReboot.onEnable(SnowLeopardReboot.java:61) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.net.URISyntaxException: Illegal character in path at index 7: plugins\SnowLeopardR//category
        at java.net.URI$Parser.fail(Unknown Source) ~[?:1.8.0_241]
        at java.net.URI$Parser.checkChars(Unknown Source) ~[?:1.8.0_241]
        at java.net.URI$Parser.parseHierarchical(Unknown Source) ~[?:1.8.0_241]
        at java.net.URI$Parser.parse(Unknown Source) ~[?:1.8.0_241]
        at java.net.URI.<init>(Unknown Source) ~[?:1.8.0_241]
        ... 15 more

**Comment by Nova41** [comment]
Can you try rolling back to the previous commit?
